name 			= "TaskForce Žaludi"; // Name of your mod
author 		    = "ReFuse"; // Affects Arma 3 Launcher, when the mod are loaded as local
logo 			= "TFZaddon\textures\logo.paa"; // Logo displayed in the main menu
logoOver 		= "TFZaddon\textures\logo_hover.paa"; // When the mouse is over, in the main menu
logoSmall 		= "TFZaddon\textures\logo.paa"; // Display in creative lists, next to the entities added by the mod
tooltip 		= "TF Žaludi";
tooltipOwned 	= "TF Žaludi"; // Tool tip displayed when the mouse is left over, in the main menu
picture 		= "TFZaddon\textures\banner.paa"; // Picture displayed from the expansions menu. Optimal size is 2048x1024
actionName 	    = "GitHub";
action 		    = "https://github.com/janzagata/TFZAddon"; // Website URL, that can be accessed from the expansions menu
overview 		= "Bunch of czech-airsoft patches."; // Supports structured text
hideName 		= 0; // Hide the extension name
hidePicture	    = 0; // Hide the extension menu
dlcColor[] 	    = {0.23,0.39,0.30,1}; // Color used for DLC stripes and backgrounds (RGBA)